export const Teams = [
    "1. FC Heidenheim 1846",
    "1. FC Kaiserslautern",
    "1. FC Köln",
    "1. FC Magdeburg",
    "1. FC Nürnberg",
    "1. FC Phönix Lübeck",
    "1. FC Saarbrücken",
    "1860 München",
    "AC Ajaccio",
    "AC Florenz",
    "AC Houilles",
    "AC Mailand",
    "AC Monza",
    "AC Omonia Nicosia",
    "AC Reggiana 1919",
    "AC Sparta Prag",
    "AD Alcorcon",
    "AD Llerenense",
    "AEK Athen",
    "AEK Larnaca",
    "AFC Bournemouth",
    "AFC Fylde",
    "AFC Wimbledon",
    "AG Caennaise",
    "AJ Auxerre",
    "AL Akhdood",
    "AL Fayha FC",
    "AL Khaleej Saihat FC",
    "AM Du Personnel Muncipal Metz",
    "AS Cittadella",
    "AS Domerat",
    "AS Fabregues",
    "AS Furiani Agliani",
    "AS Lavernose Lherm",
    "AS Monaco",
    "AS Montlouis Football",
    "AS Panazol",
    "AS Pirae",
    "AS Ptt Dijon",
    "AS Rom",
    "AS Rosador",
    "AS Saint Priest",
    "AS Saint-Étienne",
    "AS Villers Houlgate",
    "AS Vitre",
    "ASC Biesheim",
    "ASD Torres Sassari",
    "AZ Alkmaar",
    "Abha",
    "Accrington Stanley",
    "Adana Demirspor",
    "Ajax Amsterdam",
    "Al-Ahli Saudi FC",
    "Al-Fateh SC",
    "Al-Hazm",
    "Al-Hilal Saudi FC",
    "Al-Ittifaq FC",
    "Al-Ittihad Jeddah",
    "Al-Kholood",
    "Al-Nassr FC",
    "Al-Orobah",
    "Al-Qadisiyah",
    "Al-Raed Club",
    "Al-Riyadh SC",
    "Al-Shabab FC (SA)",
    "Al-Taawoun",
    "Al-Tai",
    "Al-Wehda FC",
    "Alanyaspor",
    "Albacete Balompie",
    "Albanien",
    "Aldershot Town FC",
    "Alemannia Aachen",
    "Alfreton Town FC",
    "Almere City FC",
    "Angers SCO",
    "Angouleme Charente FC",
    "Antalyaspor",
    "Antequera CF",
    "Apoel Nicosia",
    "Arandina CF",
    "Arminia Bielefeld",
    "Arosa SC",
    "Arsenal FC",
    "Asc Le Geldar",
    "Ascoli Calcio 1898 FC",
    "Aston Villa",
    "Aston Villa FC U21",
    "Astur CF",
    "Atalanta BC",
    "Athletic Bilbao",
    "Atlanta United FC",
    "Atletic Club d'Escaldes",
    "Atletico Astorga FC",
    "Atletico Lugones",
    "Atletico Sanluqueno CF",
    "Atlético Madrid",
    "Atzeneta UE",
    "Auch",
    "Aunis AFC",
    "Austin FC",
    "Aviron Bayonnais FC",
    "Avoine OCC",
    "Avs Futebol Sad",
    "B36 Torshavn",
    "BB Bodrumspor",
    "BK Häcken",
    "BSC Young Boys",
    "Bala Town FC",
    "Barakaldo CF",
    "Barnet FC",
    "Barrow AFC",
    "Bassin D'Arcachon",
    "Bayer Leverkusen",
    "Bayern München",
    "Belgien",
    "Bergerac Perigord FC",
    "Besiktas JK",
    "Birmingham City",
    "Blackburn Rovers",
    "Blagnac",
    "Boavista FC",
    "Bodö/Glimt",
    "Bologna FC",
    "Bolton Wanderers",
    "Boreham Wood FC",
    "Borussia Dortmund",
    "Borussia Dortmund II",
    "Borussia Mönchengladbach",
    "Botev Plovdiv",
    "Bourgoin J",
    "Bracknell Town FC",
    "Bradford City",
    "Breidablik Kopavogur",
    "Bremer SV 1906",
    "Brescia Calcio",
    "Brighton & Hove Albion",
    "Brighton and Hove Albion U21",
    "Bristol City",
    "Bromley FC",
    "Bröndby IF",
    "Burgos CF",
    "Burnley FC",
    "Burton Albion",
    "CA Antoniano",
    "CA Osasuna",
    "CA Pontarlier",
    "CD Arenteiro",
    "CD Aurrera de Vitoria",
    "CD Azuaga",
    "CD Baztan",
    "CD Boiro",
    "CD Bunol",
    "CD Castellon",
    "CD Cayon",
    "CD Ceuta 6 de Junio",
    "CD Covadonga",
    "CD Egues",
    "CD Gevora",
    "CD Guijuelo",
    "CD Hernan Cortes",
    "CD Leganés",
    "CD Linares",
    "CD Lugo",
    "CD Manacor",
    "CD Manchego Ciudad Real",
    "CD Mensajero",
    "CD Mirandes",
    "CD Monte",
    "CD Nacional",
    "CD Pradejon",
    "CD Promesas Edf",
    "CD Quintanar",
    "CD San Roque",
    "CD Santa Clara",
    "CD Santurtzi Ke",
    "CD Sauzal",
    "CD Sonseca",
    "CD Tenerife",
    "CD Teruel",
    "CD Tudelano",
    "CD Ursaria",
    "CD Varea",
    "CD Villamuriel",
    "CD Zirauki",
    "CDA Navalcarnero",
    "CE Andratx",
    "CE Europa",
    "CE Manresa",
    "CF Badalona Futur",
    "CF Lorca Deportiva",
    "CF Montreal",
    "CF Talavera de La Reina",
    "CF Tardienta",
    "CF Villanovense",
    "CP Cacereno SAD",
    "CS Corvinul Hunedoara",
    "CS Le Moule",
    "CS Universitatea Craiova 1948",
    "CS Volvic",
    "Cadiz CF",
    "Caernarfon Town FC",
    "Cagliari Calcio",
    "Calcio Catania",
    "Calcio Foggia",
    "Calcio Padova",
    "Camon",
    "Canet Roussillon FC",
    "Cannes",
    "Cardiff City",
    "Carlisle United",
    "Carrarese Calcio 1908",
    "Casa Pia AC",
    "Caykur Rizespor",
    "Celtic Glasgow",
    "Cercle Brügge",
    "Cesena FC",
    "Chambery SF",
    "Chantilly",
    "Charlotte FC",
    "Charlton Athletic",
    "Chaumont FC",
    "Chelsea FC U21",
    "Cheltenham Town",
    "Cherno More Varna",
    "Chesham United",
    "Chester FC",
    "Chesterfield FC",
    "Chicago Fire",
    "Chiclana CF",
    "Choisy-Au-Bac",
    "Clermont Foot",
    "Cliftonville FC",
    "Club Deportivo Eldense",
    "Colchester United",
    "Colmar",
    "Colorado Rapids",
    "Columbus Crew",
    "Como 1907",
    "Connah´s Quay Nomads FC",
    "Cosenza Calcio",
    "Coulaines",
    "Coventry City",
    "Cp Mijas-Las Lagunas",
    "Cp Parla Escuela",
    "Crawley Town",
    "Cray Valley Paper Mills FC",
    "Croix IC",
    "Crusaders FC",
    "Crystal Palace",
    "Crystal Palace FC U21",
    "Curzon Ashton FC",
    "DC United",
    "Damac Club",
    "Delfino Pescara 1936",
    "Deportivo Alaves",
    "Deportivo Murcia FC",
    "Derby County",
    "Derry City",
    "Deutschland",
    "Dieppe FC",
    "Dijon FCO",
    "Dinamo Minsk",
    "Djurgardens IF",
    "Doncaster Rovers",
    "Dänemark",
    "EA Guingamp",
    "ES Aubance",
    "ES Dolorense",
    "ES Thaon",
    "ES Villerupt Thil",
    "Eastleigh FC",
    "Eintracht Braunschweig",
    "Eintracht Frankfurt",
    "Elche CF",
    "En Avt de St Renan",
    "Energie Cottbus",
    "England",
    "Entente Feignies Aulnoye FC",
    "Entente SSG",
    "Epinal",
    "Estrela Amadora",
    "Et S Fosseenne",
    "Etoile Maritime FC",
    "Evian TG FC",
    "Exeter City",
    "Eyüpspor",
    "F91 Dudelange",
    "FA Morlaas Est Bearn",
    "FA Siauliai",
    "FC 08 Villingen",
    "FC Andorra",
    "FC Annecy",
    "FC Ararat Armenia",
    "FC Arouca",
    "FC Arsenal U21",
    "FC Astana",
    "FC Aubagne",
    "FC Augsburg",
    "FC Ballkani",
    "FC Banik Ostrava",
    "FC Barcelona",
    "FC Barnsley",
    "FC Basel",
    "FC Blackpool",
    "FC Blau-Weiss Linz",
    "FC Bondues",
    "FC Brentford",
    "FC Bristol Rovers",
    "FC Brügge",
    "FC CDA Aguilas",
    "FC CFR 1907 Cluj",
    "FC CSKA 1948",
    "FC Cambridge United",
    "FC Carl Zeiss Jena",
    "FC Cartagena",
    "FC Challans",
    "FC Chambly Oise",
    "FC Chaponnay-Marennes",
    "FC Chauray",
    "FC Chelsea",
    "FC Cincinnati",
    "FC Crewe Alexandra",
    "FC Crotone",
    "FC Dac 1904 Dunajska Streda",
    "FC Dallas",
    "FC Differdingen 03",
    "FC Dinamo Batumi",
    "FC Dinamo Tiflis",
    "FC Dinan Lehon",
    "FC Dynamo Kiew",
    "FC Empoli",
    "FC Equeurdreville Hainneville",
    "FC Erzgebirge Aue",
    "FC Espaly St Marcel",
    "FC Everton",
    "FC Everton U21",
    "FC Famalicao",
    "FC Flerien",
    "FC Fleury 91",
    "FC Flora Tallinn",
    "FC Fulham",
    "FC Geispolsheim 01",
    "FC Gillingham",
    "FC Girona",
    "FC Girondins Bordeaux",
    "FC Groningen",
    "FC Hansa Rostock",
    "FC Hauts Lyonnais",
    "FC Ingolstadt",
    "FC Kopenhagen",
    "FC Kryvbas Kriviy Rih",
    "FC Lausanne-Sport",
    "FC Libourne",
    "FC Limonest Dardilly Saint-Didier",
    "FC Loon-Plage",
    "FC Lorient",
    "FC Lugano",
    "FC Luzern",
    "FC Malaga",
    "FC Marbella",
    "FC Martigues",
    "FC Metropole Troyenne",
    "FC Metz",
    "FC Middlesbrough",
    "FC Midtjylland",
    "FC Milsami",
    "FC Minnesota United",
    "FC Mulhouse",
    "FC Nantes",
    "FC Noah",
    "FC Ordabasy",
    "FC Palermo",
    "FC Plessis Robinson",
    "FC Polissya",
    "FC Porto",
    "FC Portsmouth",
    "FC Progres Niederkorn",
    "FC Pyunik",
    "FC Reading",
    "FC Roche Saint-Genest",
    "FC Rouen",
    "FC Saburtalo Tiflis",
    "FC Saint-Meziery",
    "FC Salzburg",
    "FC Sarreguemines",
    "FC Schweighouse Sur Moder",
    "FC Seyssins",
    "FC Shakhtar Donetsk",
    "FC Sheriff Tiraspol",
    "FC Sion",
    "FC Sochaux",
    "FC Southampton",
    "FC Spartak Trnava",
    "FC St Josephs",
    "FC St. Gallen",
    "FC St. Mirren",
    "FC St. Pauli",
    "FC Stade Rennes",
    "FC Struga Trim Lum",
    "FC Sunderland",
    "FC Südtirol",
    "FC Teutonia Ottensen 1905",
    "FC Toronto",
    "FC Torpedo 2008 Kutaisi",
    "FC Torpedo Belaz Zhodino",
    "FC Turin",
    "FC Twente Enschede",
    "FC Una Strassen",
    "FC Urartu",
    "FC Utrecht",
    "FC Vaduz",
    "FC Venedig",
    "FC Viktoria 1889 Berlin",
    "FC Viktoria Köln",
    "FC Viktoria Pilsen",
    "FC Villefranche Beaujolais",
    "FC Vizela",
    "FC Walsall",
    "FC Winterthur",
    "FC Würzburger Kickers",
    "FC Zimbru Chisinau",
    "FC Zürich",
    "FCB Magpies",
    "FCSR Haguenau",
    "FK Aqtöbe",
    "FK Auda Riga",
    "FK Austria Wien",
    "FK Borac Banja Luka",
    "FK Buducnost",
    "FK Decic Tuzi",
    "FK Jungbunzlau",
    "FK Liepaja",
    "FK Mornar Bar",
    "FK Panevezys",
    "FK Partizan",
    "FK Partizani Tirana",
    "FK Radnicki 1923",
    "FK Rigas Futbola Skola",
    "FK Roter Stern Belgrad",
    "FK Sarajevo",
    "FK Shkendija",
    "FK Transinvest",
    "FK Tsc Backa Topola",
    "FK Velez Mostar",
    "FK Vojvodina",
    "FSV Mainz",
    "Fatih Karagümrük SK",
    "Fehervar FC Szekesfehervar",
    "Fenerbahce Istanbul",
    "Feralpisalò",
    "Ferencvaros Budapest",
    "Feyenoord Rotterdam",
    "Fleetwood Town",
    "Floriana FC",
    "Football Bourg-En-Bresse Peronnas 01",
    "Forest Green Rovers",
    "Fortuna Düsseldorf",
    "Fortuna Sittard",
    "Fotbal Club FCSB",
    "Frankreich",
    "Frosinone Calcio",
    "Fulham FC U21",
    "GD Chaves",
    "GD Estoril Praia",
    "GFK Tikvesh 1930",
    "GNK Dinamo Zagreb",
    "Galatasaray SK",
    "Gateshead FC",
    "Gaziantep FK",
    "Genua CFC",
    "Georgien",
    "Getafe CF",
    "Gil Vicente FC",
    "Gimnastic de Tarragona",
    "Gimnastica Segoviana",
    "Glasgow Rangers",
    "Go Ahead Eagles",
    "Golden Lion FC",
    "Granada CF",
    "Grasshopper Club Zürich",
    "Grazer AK",
    "Greifswalder FC",
    "Grenoble Foot",
    "Grimsby Town",
    "Göztepe SK",
    "HB Torshavn",
    "HJK Helsinki",
    "HNK Hajduk Split",
    "HNK Rijeka",
    "HSK Zrinjski Mostar",
    "Hallescher FC",
    "Hamburger SV",
    "Hamrun Spartans FC",
    "Hannover 96",
    "Hannover 96 II",
    "Hapoel Beer Sheva FC",
    "Harrogate Town",
    "Hatayspor",
    "Heart of Midlothian FC",
    "Hellas Verona",
    "Heracles Almelo",
    "Hercules CF",
    "Hereford FC",
    "Hertha BSC",
    "Hienghene Sport",
    "Holstein Kiel",
    "Horsham FC",
    "Houston Dynamo",
    "Huddersfield Town",
    "Hull City",
    "Hyeres FC",
    "IF Elfsborg",
    "Inter Club de Escaldes",
    "Inter Mailand",
    "Inter Miami CF",
    "Ipswich Town",
    "Isloch",
    "Istanbul Basaksehir FK",
    "Istanbulspor AS",
    "Italien",
    "Itancourt Neuville",
    "JA Isle Football",
    "JK Tallinna Kalev",
    "Jagiellonia Bialystok",
    "Jarville JF",
    "Js Douvres",
    "Jura Dolois Fussball",
    "Jura Sud Foot",
    "Juventus Turin",
    "KAA Gent",
    "KF Drita",
    "KF Egnatia Rrogozhine",
    "KF Llapi",
    "KF Malisheva",
    "KF Tirana",
    "KF Vllaznia Shkoder",
    "KI Klaksvik",
    "Karlsruher SC",
    "Kasimpasa",
    "Kayserispor",
    "Kidderminster Harriers FC",
    "Kilmarnock FC",
    "Konyaspor",
    "Kroatien",
    "Kuopion Palloseura",
    "LASK Linz",
    "LB Chateauroux",
    "LR Vicenza",
    "La France D Aizenay",
    "Larne FC",
    "Lazio Rom",
    "Le Havre AC",
    "Le Puy Foot 43 Auvergne",
    "Leeds United",
    "Legia Warschau",
    "Leicester City",
    "Leicester City U21",
    "Les Herbiers",
    "Levadia Tallinn",
    "Levante UD",
    "Leyton Orient",
    "Lincoln City",
    "Lincoln Red Imps FC",
    "Linfield FC",
    "Liverpool FC",
    "Liverpool FC U21",
    "Longueau ESC",
    "Los Angeles FC",
    "Los Angeles Galaxy",
    "Louhans Cuiseaux",
    "Ludogorets 1945 Razgrad",
    "Luton Town",
    "Lyon La Duchère",
    "MFk Ruzomberok",
    "MKE Ankaragucu",
    "MSV Duisburg",
    "Maccabi Haifa FC",
    "Maccabi Petah Tikva FC",
    "Maccabi Tel Aviv FC",
    "Maidenhead United FC",
    "Maidstone United FC",
    "Malmö FF",
    "Manchester City",
    "Manchester City FC U21",
    "Manchester United",
    "Manchester United FC U21",
    "Manises CF",
    "Mansfield Town",
    "Mantova 1911",
    "Marine FC",
    "Marsaxlokk FC",
    "Melilla CD",
    "Millwall FC",
    "Milton Keynes Dons",
    "Modena FC",
    "Molde FK",
    "Montdidier AC",
    "Montpellier HSC",
    "Morecambe FC",
    "Moreirense FC",
    "NAC Breda",
    "NEC Nijmegen",
    "NK Bravo",
    "NK Celje",
    "NK Maribor",
    "NK Olimpija Ljubljana",
    "NK Osijek",
    "Nashville SC",
    "Naxara CD",
    "Neman Grodno",
    "Neuville Sur Saone",
    "New England Revolution",
    "New York City FC",
    "New York Red Bulls",
    "Newcastle United",
    "Newcastle United FC U21",
    "Newport County AFC",
    "Niederlande",
    "Nimes Olympique",
    "Noeux Les Mines",
    "Noisy Le Sec",
    "Northampton Town",
    "Norwich City",
    "Nottingham Forest",
    "Nottingham Forest FC U21",
    "Notts County",
    "OGC Nizza",
    "OSC Lille",
    "Offenbacher FC Kickers 1901",
    "Oldham Athletic",
    "Olympiakos Piräus",
    "Olympique Ales",
    "Olympique Lyon",
    "Olympique Marseille",
    "Ontinena CF",
    "Orihuela CF",
    "Orlando City SC",
    "Oxford United",
    "PAOK Thessaloniki",
    "PEC Zwolle",
    "PSV Eindhoven",
    "Pafos FC",
    "Paide Linnameeskond",
    "Paksi FC",
    "Panathinaikos Athen",
    "Paris FC",
    "Paris Saint-Germain",
    "Parma Calcio",
    "Pau FC",
    "Pd Ergue Gaberic",
    "Pd Santa Eulalia",
    "Pendikspor",
    "Peterborough United",
    "Petrocub Hincesti",
    "Philadelphia Union",
    "Plougastel FC",
    "Plymouth Argyle",
    "Polen",
    "Pontivy GSI",
    "Port Vale FC",
    "Portimonense SC",
    "Portland Timbers",
    "Portugal",
    "Preston North End",
    "Puskas Akademia FC Felcsut",
    "Qarabag FK",
    "Queens Park Rangers",
    "RB Leipzig",
    "RC Calais",
    "RC Celta de Vigo",
    "RC Deportivo La Coruna",
    "RC Doullens",
    "RC Lens",
    "RC Recreativo de Huelva",
    "RC Strasbourg Alsace",
    "RCD Espanyol Barcelona",
    "RCD Mallorca",
    "RKC Waalwijk",
    "RSC Anderlecht",
    "RW Essen",
    "Racing Club De France 92",
    "Racing Club de Ferrol",
    "Racing Santander",
    "Ramsgate FC",
    "Rayo Vallecano",
    "Real Aviles CF",
    "Real Betis Balompie",
    "Real Jaén CF",
    "Real Madrid",
    "Real Murcia CF",
    "Real Oviedo",
    "Real Salt Lake",
    "Real Saragossa",
    "Real Sociedad",
    "Real Valladolid",
    "Red Star FC",
    "Reims Sainte-Anne",
    "Riga FC",
    "Rio Ave FC",
    "Roannais Foot 42",
    "Rodez Aveyron",
    "Rotherham United",
    "Rumänien",
    "SC Amiens",
    "SC Austria Lustenau",
    "SC Bastia",
    "SC Braga",
    "SC Dnipro-1",
    "SC Farense",
    "SC Freiburg",
    "SC Freiburg II",
    "SC Heerenveen",
    "SC Paderborn 07",
    "SC Pisa",
    "SC Preußen 06 Münster",
    "SC Verl",
    "SCR Altach",
    "SD Amorebieta",
    "SD Compostela",
    "SD Eibar",
    "SD Gernika Club",
    "SD Huesca",
    "SD Ponferradina",
    "SD Tarazona",
    "SG Dynamo Dresden",
    "SK Austria Klagenfurt",
    "SK Brann",
    "SK Rapid Wien",
    "SK Slavia Prag",
    "SK Slovan Bratislava",
    "SK Sturm Graz",
    "SL Benfica",
    "SM Caen",
    "SO Cholet",
    "SO Romorantin",
    "SP La Fiorita",
    "SP Tre Penne",
    "SS Juve Stabia",
    "SS Virtus",
    "SSC Bari",
    "SSC Neapel",
    "SSV Jahn Regensburg",
    "SSV Ulm 1846",
    "SV 07 Elversberg",
    "SV Darmstadt 98",
    "SV Meppen 1912",
    "SV Sandhausen",
    "SV Waldhof Mannheim 07",
    "SV Wehen Wiesbaden",
    "Sa Le Quesnoy",
    "Sabah FC Masazir",
    "Saint Aubin Guerande FC",
    "Saint Denis FC",
    "Saint Denis US",
    "Saint Louis City SC",
    "Saint Michel FC 91",
    "Saint Patrick´s Athletic",
    "Salford City",
    "Sampdoria Genua",
    "Samsunspor",
    "San Jose Earthquakes",
    "San Tirso SD",
    "Sassuolo Calcio",
    "Saumur Olympique",
    "Scarborough Athletic",
    "Schalke 04",
    "Schottland",
    "Schweiz",
    "Seattle Sounders",
    "Selaya FC",
    "Serbien",
    "Servette FC",
    "Sestao River Club",
    "Sevilla FC",
    "Shamrock Rovers",
    "Sheffield United FC",
    "Sheffield Wednesday",
    "Shelbourne FC",
    "Sheppey United FC",
    "Shrewsbury Town",
    "Silkeborg IF",
    "Sivasspor",
    "Sliema Wanderers FC",
    "Slough Town FC",
    "Slowakei",
    "Slowenien",
    "Solihull Moors FC",
    "SpVgg Greuther Fürth",
    "SpVgg Unterhaching",
    "Spanien",
    "Sparta Rotterdam",
    "Spezia Calcio",
    "Sport Union Dives-Cabourg",
    "Sporting Gijon",
    "Sporting Kansas City",
    "Sporting Lissabon",
    "Sporting de Mahon",
    "Squadra Valincu Alta Rocca Rizzanese",
    "St. Paimpolais",
    "Stade Brestois 29",
    "Stade Briochin",
    "Stade Lavallois MFC",
    "Stade Mayennais FC",
    "Stade Plabennecois",
    "Stade Poitevin FC",
    "Stade Pontivyen",
    "Stade Reims",
    "Ste S Educ Phys Hombourg Haut",
    "Stevenage FC",
    "Stjarnan Gardabae",
    "Stockport County FC",
    "Stoke City",
    "Sumgayit FK",
    "Sutton United FC",
    "Swansea City",
    "Swindon Town",
    "TA Rennes",
    "TSG Hoffenheim",
    "TSV Hartberg",
    "TSV Schott Mainz",
    "TUS Koblenz 1911",
    "Tampereen Ilves",
    "Ternana Calcio",
    "Terrassa FC",
    "The New Saints FC",
    "Thionville Lusitanos",
    "Tobol Kostanay",
    "Torcy",
    "Tottenham Hotspur",
    "Tottenham Hotspur FC U21",
    "Toulouse FC",
    "Toulouse Metropole",
    "Trabzonspor",
    "Tranmere Rovers FC",
    "Trelissac FC",
    "Tromsö IL",
    "Troyes AC",
    "Tschechien",
    "Turegano CF",
    "Türkei",
    "UCAM Murcia",
    "UD Almeria",
    "UD Barbastro",
    "UD Ibiza",
    "UD Las Palmas",
    "UD Logrones",
    "UD Melilla",
    "UD Playas de Sotavento",
    "UD Rotlet Molinar",
    "UD San Pedro",
    "UE Rubi",
    "UE Santa Coloma",
    "UF Maconnais",
    "US Avellino",
    "US Avranches",
    "US Bleriot Plage",
    "US Boulogne",
    "US Castaneenne",
    "US Catanzaro",
    "US Chateaugiron",
    "US Concarneau",
    "US Cremonese",
    "US Feurs",
    "US Forbach",
    "US Fougeres",
    "US Laon",
    "US Le Pays Du Valois",
    "US Lecce",
    "US Liffre",
    "US Orleans 45",
    "US Provin",
    "US Quevilly-Rouen Metropole",
    "US Revel",
    "US Saint Omer",
    "US Saint-Malo",
    "US Salernitana",
    "US Sarre Union",
    "US St Philbert de Grandlieu",
    "US Villejuif",
    "USL Dunkerque",
    "Udinese Calcio",
    "Ukraine",
    "Ungarn",
    "Unio Esportiva Vic",
    "Union Berlin",
    "Union Cosnoise Sportive",
    "Union Saint-Gilloise",
    "Union Zona Norte",
    "Unionistas de Salamanca CF",
    "Utebo FC",
    "Vaasan Palloseura",
    "Valencia CF",
    "Valenciennes FC",
    "Valur Reykjavik",
    "Vancouver Whitecaps FC",
    "Velay FC",
    "Vendee Poire-Sur-Vie Football",
    "VfB Lübeck",
    "VfB Stuttgart",
    "VfB Stuttgart II",
    "VfL 1899 Osnabrück",
    "VfL Bochum",
    "VfL Sportfreunde Lotte 1929",
    "VfL Wolfsburg",
    "VfR 1921 Aalen",
    "VfV 06 Hildesheim",
    "Vierzon FC",
    "Vikingur Gota",
    "Vikingur Reykjavik",
    "Villarreal CF",
    "Villenave",
    "Vilnius FK Zalgiris",
    "Virtus Entella",
    "Vitoria Guimaraes",
    "WKS Slask Wroclaw",
    "WSG Tirol",
    "Watford FC",
    "Werder Bremen",
    "West Bromwich Albion",
    "West Ham United",
    "West Ham United FC U21",
    "Whitby Town",
    "Wigan Athletic",
    "Willem II Tilburg",
    "Wisla Krakau",
    "Woking FC",
    "Wolfsberger AC",
    "Wolverhampton Wanderers",
    "Wolverhampton Wanderers FC U21",
    "Worksop Town",
    "Worthing FC",
    "Wrexham AFC",
    "Wycombe Wanderers",
    "Yeclano Deportivo",
    "Yeovil Town",
    "York City FC",
    "Yverdon Sport FC",
    "Zamora CF",
    "Zira FK",
    "Österreich",
] as const;

export type Team = typeof Teams[number];

export const Tournaments = [
    "2. Bundesliga 23/24",
    "2. Bundesliga 24/25",
    "3. Liga 23/24",
    "3. Liga 24/25",
    "Bundesliga 23/24",
    "Bundesliga 24/25",
    "Bundesliga AUT 23/24",
    "Bundesliga AUT 24/25",
    "Community Shield 2024",
    "Copa del Rey 23/24",
    "Copa del Rey 24/25",
    "Coppa Italia 23/24",
    "Coppa Italia 24/25",
    "Coupe de France 23/24",
    "DFB Pokal 24/25",
    "EFL Cup 23/24",
    "EFL Cup 24/25",
    "EFL Trophy 24/25",
    "Eredivisie 24/25",
    "Europameisterschaft 2024",
    "FA Cup 23/24",
    "LaLiga 24/25",
    "Liga Portugal 23/24",
    "Liga Portugal 24/25",
    "Ligue 1 24/25",
    "Major League Soccer 2024",
    "Premier League 24/25",
    "Saudi Prof. League 23/24",
    "Saudi Prof. League 24/25",
    "Serie A 23/24",
    "Serie A 24/25",
    "Super Cup 23/24",
    "Super League 24/25",
    "Supercopa 2025",
    "Supercup 2024",
    "Supercup ESP 2024",
    "Süper Lig 23/24",
    "Süper Lig 24/25",
    "Trophée des Champions 2024",
    "UEFA Champions League 24/25",
    "UEFA Conference League 24/25",
    "UEFA Europa League 24/25",
    "UEFA Super Cup 2024",
] as const;

export type Tournament = typeof Tournaments[number];
