export const teams = [
  "AD Alcorcon",
  "Borussia Dortmund II",
  "Chambery SF",
  "FC Metz",
  "Cesena FC",
  "Stade Lavallois MFC",
  "SK Brann",
  "Whitby Town",
  "Fenerbahce Istanbul",
  "Barrow AFC",
  "Al-Riyadh SC",
  "Alfreton Town FC",
  "US Villejuif",
  "Burgos CF",
  "CD Sauzal",
  "Oldham Athletic",
  "Crystal Palace",
  "US Forbach",
  "Adana Demirspor",
  "CD Ursaria",
  "Shrewsbury Town",
  "Udinese Calcio",
  "FC Equeurdreville Hainneville",
  "FC Venedig",
  "Bayer Leverkusen",
  "Al-Raed Club",
  "Slough Town FC",
  "Ferencvaros Budapest",
  "AC Monza",
  "Houston Dynamo",
  "Hapoel Beer Sheva FC",
  "Brescia Calcio",
  "CD Santa Clara",
  "SpVgg Greuther Fürth",
  "CD Sonseca",
  "Ste S Educ Phys Hombourg Haut",
  "FC Midtjylland",
  "AS Saint Priest",
  "USL Dunkerque",
  "Feyenoord Rotterdam",
  "Worksop Town",
  "FC Cartagena",
  "CD Santurtzi Ke",
  "Harrogate Town",
  "Willem II Tilburg",
  "Hull City",
  "Atletico Sanluqueno CF",
  "Vikingur Gota",
  "Cherno More Varna",
  "Botev Plovdiv",
  "Newcastle United FC U21",
  "CD Cayon",
  "Gimnastic de Tarragona",
  "SK Slovan Bratislava",
  "Silkeborg IF",
  "CD Tenerife",
  "Port Vale FC",
  "Burnley FC",
  "US Orleans 45",
  "Boavista FC",
  "Huddersfield Town",
  "Torcy",
  "Sport Union Dives-Cabourg",
  "Shelbourne FC",
  "FC Malaga",
  "Norwich City",
  "FC Viktoria Pilsen",
  "FK Radnicki 1923",
  "CD Promesas Edf",
  "FK Tsc Backa Topola",
  "Legia Warschau",
  "Deutschland",
  "MSV Duisburg",
  "Sporting Gijon",
  "OSC Lille",
  "SC Paderborn 07",
  "Cannes",
  "Bourgoin J",
  "RCD Espanyol Barcelona",
  "Grasshopper Club Zürich",
  "SCR Altach",
  "FC CSKA 1948",
  "1860 München",
  "Austin FC",
  "NAC Breda",
  "JK Tallinna Kalev",
  "FC Annecy",
  "Heracles Almelo",
  "Holstein Kiel",
  "US Catanzaro",
  "Antequera CF",
  "Kasimpasa",
  "KAA Gent",
  "RC Deportivo La Coruna",
  "KF Tirana",
  "Js Douvres",
  "Liverpool FC U21",
  "Columbus Crew",
  "Rumänien",
  "Seattle Sounders",
  "Barakaldo CF",
  "Inter Club de Escaldes",
  "Horsham FC",
  "Aviron Bayonnais FC",
  "Gimnastica Segoviana",
  "Sliema Wanderers FC",
  "Queens Park Rangers",
  "CD Guijuelo",
  "AC Ajaccio",
  "NK Maribor",
  "FC Villefranche Beaujolais",
  "Alanyaspor",
  "Hercules CF",
  "Kuopion Palloseura",
  "Borussia Mönchengladbach",
  "AG Caennaise",
  "US Liffre",
  "Swindon Town",
  "West Ham United",
  "Bracknell Town FC",
  "CD Azuaga",
  "Hallescher FC",
  "Vaasan Palloseura",
  "Paksi FC",
  "Bolton Wanderers",
  "Salford City",
  "KI Klaksvik",
  "Arandina CF",
  "New York Red Bulls",
  "SM Caen",
  "GNK Dinamo Zagreb",
  "SD Eibar",
  "FK Decic Tuzi",
  "US Fougeres",
  "AM Du Personnel Muncipal Metz",
  "FC Shakhtar Donetsk",
  "SO Romorantin",
  "FC Winterthur",
  "FC Ingolstadt",
  "Grazer AK",
  "Choisy-Au-Bac",
  "Hatayspor",
  "Et S Fosseenne",
  "UD Rotlet Molinar",
  "Chicago Fire",
  "NK Osijek",
  "FC Hauts Lyonnais",
  "AD Llerenense",
  "New England Revolution",
  "Clermont Foot",
  "CE Europa",
  "FC Sunderland",
  "FC Blau-Weiss Linz",
  "Angers SCO",
  "Al-Ittihad Jeddah",
  "Levadia Tallinn",
  "CS Volvic",
  "Energie Cottbus",
  "Albanien",
  "UD Almeria",
  "TA Rennes",
  "Österreich",
  "GD Chaves",
  "FC Loon-Plage",
  "FC Andorra",
  "Philadelphia Union",
  "Red Star FC",
  "Etoile Maritime FC",
  "Arsenal FC",
  "CF Tardienta",
  "Saint Michel FC 91",
  "SV 07 Elversberg",
  "US Chateaugiron",
  "Sivasspor",
  "Bradford City",
  "Nashville SC",
  "Apoel Nicosia",
  "St. Paimpolais",
  "Servette FC",
  "FC CFR 1907 Cluj",
  "CA Osasuna",
  "Moreirense FC",
  "1. FC Phönix Lübeck",
  "1. FC Heidenheim 1846",
  "FC Sochaux",
  "Trabzonspor",
  "SK Austria Klagenfurt",
  "FC Rouen",
  "FC Struga Trim Lum",
  "FC Chambly Oise",
  "US Cremonese",
  "Schweiz",
  "Al-Hilal Saudi FC",
  "Frosinone Calcio",
  "Real Saragossa",
  "FC Stade Rennes",
  "Crawley Town",
  "Abha",
  "IF Elfsborg",
  "Curzon Ashton FC",
  "AS Fabregues",
  "US Sarre Union",
  "SD Compostela",
  "HSK Zrinjski Mostar",
  "Spanien",
  "FC Hansa Rostock",
  "SV Sandhausen",
  "Fortuna Sittard",
  "FC Mulhouse",
  "Al-Wehda FC",
  "Union Saint-Gilloise",
  "Al-Orobah",
  "FC Luzern",
  "Stockport County FC",
  "SC Braga",
  "Canet Roussillon FC",
  "Maccabi Tel Aviv FC",
  "Real Murcia CF",
  "Jagiellonia Bialystok",
  "Linfield FC",
  "Real Betis Balompie",
  "Troyes AC",
  "FC Salzburg",
  "RKC Waalwijk",
  "UD Logrones",
  "Charlotte FC",
  "FC Augsburg",
  "FC Urartu",
  "Milton Keynes Dons",
  "Malmö FF",
  "Belgien",
  "Sa Le Quesnoy",
  "US Bleriot Plage",
  "Caernarfon Town FC",
  "Georgien",
  "FC Basel",
  "Racing Club De France 92",
  "Blagnac",
  "Carlisle United",
  "Arminia Bielefeld",
  "Bremer SV 1906",
  "ES Dolorense",
  "CD Zirauki",
  "Entente Feignies Aulnoye FC",
  "Louhans Cuiseaux",
  "FC Empoli",
  "CS Le Moule",
  "Connah´s Quay Nomads FC",
  "CD Baztan",
  "Leicester City",
  "Aunis AFC",
  "Leyton Orient",
  "Los Angeles Galaxy",
  "Deportivo Murcia FC",
  "Sporting Kansas City",
  "Olympique Marseille",
  "Vitoria Guimaraes",
  "Union Cosnoise Sportive",
  "SS Virtus",
  "Stade Mayennais FC",
  "CF Badalona Futur",
  "Stade Reims",
  "FK Austria Wien",
  "San Tirso SD",
  "Carrarese Calcio 1908",
  "Como 1907",
  "FC Toronto",
  "Notts County",
  "SV Waldhof Mannheim 07",
  "Tranmere Rovers FC",
  "Northampton Town",
  "FC Polissya",
  "Maccabi Haifa FC",
  "FC Barnsley",
  "Parma Calcio",
  "AC Sparta Prag",
  "SG Dynamo Dresden",
  "Naxara CD",
  "FC Pyunik",
  "RC Strasbourg Alsace",
  "SK Rapid Wien",
  "Liverpool FC",
  "Real Oviedo",
  "Orihuela CF",
  "SC Verl",
  "Zamora CF",
  "Valenciennes FC",
  "UD Barbastro",
  "Fehervar FC Szekesfehervar",
  "Thionville Lusitanos",
  "CDA Navalcarnero",
  "Bologna FC",
  "Albacete Balompie",
  "Inter Miami CF",
  "Boreham Wood FC",
  "FC Utrecht",
  "FC Famalicao",
  "Stade Poitevin FC",
  "Scarborough Athletic",
  "Al-Kholood",
  "VfL 1899 Osnabrück",
  "FK Sarajevo",
  "Lyon La Duchère",
  "AEK Larnaca",
  "Damac Club",
  "Almere City FC",
  "Utebo FC",
  "FC Milsami",
  "FC St Josephs",
  "Ludogorets 1945 Razgrad",
  "ASC Biesheim",
  "SV Wehen Wiesbaden",
  "FC Metropole Troyenne",
  "AS Furiani Agliani",
  "Bromley FC",
  "Neman Grodno",
  "UE Rubi",
  "FC Middlesbrough",
  "FC Cambridge United",
  "ES Aubance",
  "Niederlande",
  "Portugal",
  "PSV Eindhoven",
  "Antalyaspor",
  "SSC Bari",
  "TSG Hoffenheim",
  "Levante UD",
  "CD Aurrera de Vitoria",
  "Sutton United FC",
  "Granada CF",
  "FC Gillingham",
  "CF Villanovense",
  "Hannover 96 II",
  "TSV Hartberg",
  "Mansfield Town",
  "Racing Club de Ferrol",
  "FC Plessis Robinson",
  "Polen",
  "Hannover 96",
  "CD Villamuriel",
  "ES Thaon",
  "Pendikspor",
  "AC Reggiana 1919",
  "US Castaneenne",
  "Union Zona Norte",
  "Qarabag FK",
  "Cardiff City",
  "Stoke City",
  "CD Pradejon",
  "FC Bondues",
  "FC Crewe Alexandra",
  "CD Tudelano",
  "AS Villers Houlgate",
  "Olympique Lyon",
  "Dijon FCO",
  "CD Nacional",
  "Atalanta BC",
  "KF Egnatia Rrogozhine",
  "Djurgardens IF",
  "WKS Slask Wroclaw",
  "VfR 1921 Aalen",
  "FC Challans",
  "Ontinena CF",
  "SC Amiens",
  "Chester FC",
  "HJK Helsinki",
  "SC Dnipro-1",
  "Luton Town",
  "FC Viktoria Köln",
  "Floriana FC",
  "Dieppe FC",
  "Saint Louis City SC",
  "Ascoli Calcio 1898 FC",
  "Zira FK",
  "Kroatien",
  "Molde FK",
  "VfB Stuttgart II",
  "FK Auda Riga",
  "Shamrock Rovers",
  "Grenoble Foot",
  "Wolfsberger AC",
  "AL Khaleej Saihat FC",
  "CD Varea",
  "Union Berlin",
  "AFC Wimbledon",
  "AS Ptt Dijon",
  "FC Espaly St Marcel",
  "FC Una Strassen",
  "Ajax Amsterdam",
  "Istanbul Basaksehir FK",
  "Saint Aubin Guerande FC",
  "UD Playas de Sotavento",
  "US Salernitana",
  "FC Carl Zeiss Jena",
  "Werder Bremen",
  "FC Twente Enschede",
  "Sassuolo Calcio",
  "Calcio Foggia",
  "FK Roter Stern Belgrad",
  "RC Celta de Vigo",
  "Tottenham Hotspur FC U21",
  "US Concarneau",
  "AS Lavernose Lherm",
  "Wycombe Wanderers",
  "AS Rom",
  "FC Saburtalo Tiflis",
  "Sheppey United FC",
  "Sabah FC Masazir",
  "FC Everton",
  "Al-Ittifaq FC",
  "FC Spartak Trnava",
  "Sevilla FC",
  "CD Lugo",
  "FC Chaponnay-Marennes",
  "NK Bravo",
  "FCSR Haguenau",
  "Exeter City",
  "AFC Fylde",
  "Stade Pontivyen",
  "FC Ballkani",
  "Nimes Olympique",
  "CF Talavera de La Reina",
  "CD San Roque",
  "B36 Torshavn",
  "NEC Nijmegen",
  "Avs Futebol Sad",
  "Al-Fateh SC",
  "Al-Ahli Saudi FC",
  "Olympiakos Piräus",
  "Peterborough United",
  "AS Monaco",
  "FC Seyssins",
  "Galatasaray SK",
  "FC CDA Aguilas",
  "Sumgayit FK",
  "Eyüpspor",
  "Go Ahead Eagles",
  "KF Drita",
  "Solihull Moors FC",
  "Real Salt Lake",
  "FC St. Gallen",
  "Isloch",
  "NK Celje",
  "LASK Linz",
  "Velay FC",
  "Al-Hazm",
  "Colchester United",
  "FC Lugano",
  "FC Brügge",
  "Modena FC",
  "Orlando City SC",
  "Yeovil Town",
  "Pau FC",
  "CF Lorca Deportiva",
  "RC Doullens",
  "CD Bunol",
  "FC Walsall",
  "Al-Nassr FC",
  "FC Fleury 91",
  "SD Amorebieta",
  "Panathinaikos Athen",
  "SV Meppen 1912",
  "Longueau ESC",
  "Sheffield Wednesday",
  "Delfino Pescara 1936",
  "Feralpisalò",
  "US Le Pays Du Valois",
  "Lincoln Red Imps FC",
  "FC Dinan Lehon",
  "FC Chauray",
  "Los Angeles FC",
  "FC Arsenal U21",
  "Tampereen Ilves",
  "Samsunspor",
  "LB Chateauroux",
  "Selaya FC",
  "FC Aubagne",
  "KF Vllaznia Shkoder",
  "FC Martigues",
  "UCAM Murcia",
  "Golden Lion FC",
  "1. FC Saarbrücken",
  "CD Mirandes",
  "Al-Taawoun",
  "Chelsea FC U21",
  "Brighton and Hove Albion U21",
  "RC Calais",
  "FC Arouca",
  "CD Manchego Ciudad Real",
  "Maccabi Petah Tikva FC",
  "Valur Reykjavik",
  "Vilnius FK Zalgiris",
  "FC 08 Villingen",
  "Rayo Vallecano",
  "FC Sheriff Tiraspol",
  "CD Quintanar",
  "Arosa SC",
  "FC Reading",
  "SC Farense",
  "Sampdoria Genua",
  "FK Jungbunzlau",
  "Sporting de Mahon",
  "AS Vitre",
  "Deportivo Alaves",
  "Olympique Ales",
  "FC Chelsea",
  "AC Omonia Nicosia",
  "FC Dynamo Kiew",
  "Puskas Akademia FC Felcsut",
  "Lincoln City",
  "Wisla Krakau",
  "Noeux Les Mines",
  "UD Melilla",
  "Marsaxlokk FC",
  "FC Viktoria 1889 Berlin",
  "FC Kryvbas Kriviy Rih",
  "San Jose Earthquakes",
  "FC Nantes",
  "US Boulogne",
  "Gateshead FC",
  "Turegano CF",
  "US Saint Omer",
  "Chesterfield FC",
  "MFk Ruzomberok",
  "TUS Koblenz 1911",
  "Manises CF",
  "Spezia Calcio",
  "SC Pisa",
  "1. FC Kaiserslautern",
  "Toulouse Metropole",
  "Cliftonville FC",
  "FC Turin",
  "Auch",
  "Tottenham Hotspur",
  "Pafos FC",
  "FC Barcelona",
  "Vikingur Reykjavik",
  "Hienghene Sport",
  "Caykur Rizespor",
  "CD Egues",
  "SD Huesca",
  "Chaumont FC",
  "MKE Ankaragucu",
  "Borussia Dortmund",
  "Jura Sud Foot",
  "Itancourt Neuville",
  "FSV Mainz",
  "CA Antoniano",
  "Atzeneta UE",
  "SP Tre Penne",
  "Aston Villa",
  "AS Pirae",
  "TSV Schott Mainz",
  "Manchester United FC U21",
  "FK Velez Mostar",
  "FC Vizela",
  "Unio Esportiva Vic",
  "Atlético Madrid",
  "Glasgow Rangers",
  "FC Kopenhagen",
  "FK Partizani Tirana",
  "CA Pontarlier",
  "FK Aqtöbe",
  "En Avt de St Renan",
  "FK Partizan",
  "FC Girondins Bordeaux",
  "Saumur Olympique",
  "Cagliari Calcio",
  "Watford FC",
  "Entente SSG",
  "FC Torpedo Belaz Zhodino",
  "FK Buducnost",
  "Inter Mailand",
  "Ternana Calcio",
  "CD Castellon",
  "Konyaspor",
  "Maidstone United FC",
  "FC Flora Tallinn",
  "FC Noah",
  "Newcastle United",
  "AC Houilles",
  "CD Linares",
  "Serbien",
  "Blackburn Rovers",
  "Saint Denis FC",
  "AL Akhdood",
  "Heart of Midlothian FC",
  "FC Girona",
  "LR Vicenza",
  "FC Porto",
  "FC Banik Ostrava",
  "Stade Briochin",
  "Accrington Stanley",
  "Offenbacher FC Kickers 1901",
  "Chesham United",
  "Oxford United",
  "Leeds United",
  "FC Flerien",
  "FC Blackpool",
  "FC Astana",
  "HNK Hajduk Split",
  "Morecambe FC",
  "Paris FC",
  "Mantova 1911",
  "FC Ordabasy",
  "JA Isle Football",
  "Genua CFC",
  "1. FC Köln",
  "SD Tarazona",
  "Saint Patrick´s Athletic",
  "Al-Tai",
  "Sporting Lissabon",
  "Worthing FC",
  "Villenave",
  "Yeclano Deportivo",
  "FC Limonest Dardilly Saint-Didier",
  "CD Gevora",
  "AEK Athen",
  "The New Saints FC",
  "Wolverhampton Wanderers FC U21",
  "Dänemark",
  "Leicester City U21",
  "FC Groningen",
  "West Bromwich Albion",
  "Petrocub Hincesti",
  "Ungarn",
  "UF Maconnais",
  "Greifswalder FC",
  "FC Brentford",
  "FK Vojvodina",
  "Casa Pia AC",
  "Manchester City",
  "Evian TG FC",
  "Tromsö IL",
  "Neuville Sur Saone",
  "AFC Bournemouth",
  "CD Hernan Cortes",
  "SL Benfica",
  "AL Fayha FC",
  "Atletic Club d'Escaldes",
  "Millwall FC",
  "Ipswich Town",
  "Marine FC",
  "AS Cittadella",
  "AZ Alkmaar",
  "Fatih Karagümrük SK",
  "FC Libourne",
  "VfB Lübeck",
  "US Feurs",
  "Grimsby Town",
  "Montdidier AC",
  "Saint Denis US",
  "FC Dallas",
  "FC Vaduz",
  "Cray Valley Paper Mills FC",
  "Tobol Kostanay",
  "RCD Mallorca",
  "FCB Magpies",
  "Eintracht Frankfurt",
  "Swansea City",
  "FK Panevezys",
  "CD Manacor",
  "CD Monte",
  "Jarville JF",
  "Besiktas JK",
  "PEC Zwolle",
  "Bayern München",
  "Toulouse FC",
  "AC Florenz",
  "Athletic Bilbao",
  "Real Sociedad",
  "Colmar",
  "CE Andratx",
  "AS Panazol",
  "Getafe CF",
  "CD Mensajero",
  "VfV 06 Hildesheim",
  "Aldershot Town FC",
  "SSV Ulm 1846",
  "UD San Pedro",
  "VfL Bochum",
  "Breidablik Kopavogur",
  "CF Montreal",
  "US Revel",
  "F91 Dudelange",
  "SP La Fiorita",
  "Cp Mijas-Las Lagunas",
  "OGC Nizza",
  "Rotherham United",
  "Fleetwood Town",
  "Crusaders FC",
  "AC Mailand",
  "Maidenhead United FC",
  "CS Corvinul Hunedoara",
  "Plougastel FC",
  "Tschechien",
  "FC Sion",
  "Manchester City FC U21",
  "US Saint-Malo",
  "RC Lens",
  "Villarreal CF",
  "Crystal Palace FC U21",
  "ES Villerupt Thil",
  "Rio Ave FC",
  "Hamburger SV",
  "Avoine OCC",
  "FC St. Mirren",
  "Stjarnan Gardabae",
  "SC Austria Lustenau",
  "KF Malisheva",
  "US Provin",
  "FC Saint-Meziery",
  "FC Marbella",
  "Plymouth Argyle",
  "Vendee Poire-Sur-Vie Football",
  "Paris Saint-Germain",
  "Alemannia Aachen",
  "Hyeres FC",
  "Cp Parla Escuela",
  "Kidderminster Harriers FC",
  "Juventus Turin",
  "Manchester United",
  "Vancouver Whitecaps FC",
  "Astur CF",
  "Le Puy Foot 43 Auvergne",
  "New York City FC",
  "Unionistas de Salamanca CF",
  "FC Zürich",
  "US Lecce",
  "AS Saint-Étienne",
  "CD Teruel",
  "Stevenage FC",
  "Calcio Catania",
  "SpVgg Unterhaching",
  "WSG Tirol",
  "FC Southampton",
  "Wolverhampton Wanderers",
  "Lazio Rom",
  "Nottingham Forest",
  "Rodez Aveyron",
  "FC Bristol Rovers",
  "Woking FC",
  "Roannais Foot 42",
  "FC Lorient",
  "Portland Timbers",
  "Coventry City",
  "PAOK Thessaloniki",
  "Charlton Athletic",
  "US Avranches",
  "Eintracht Braunschweig",
  "SV Darmstadt 98",
  "Le Havre AC",
  "Eastleigh FC",
  "Derby County",
  "CD Covadonga",
  "FC Zimbru Chisinau",
  "FC Progres Niederkorn",
  "Montpellier HSC",
  "Bröndby IF",
  "FC Palermo",
  "Real Jaén CF",
  "Fotbal Club FCSB",
  "FC Dinamo Tiflis",
  "Atletico Astorga FC",
  "GD Estoril Praia",
  "Valencia CF",
  "Karlsruher SC",
  "FC Lausanne-Sport",
  "1. FC Nürnberg",
  "VfB Stuttgart",
  "1. FC Magdeburg",
  "US Quevilly-Rouen Metropole",
  "ASD Torres Sassari",
  "Fortuna Düsseldorf",
  "CD Boiro",
  "Doncaster Rovers",
  "Portimonense SC",
  "York City FC",
  "Wigan Athletic",
  "Istanbulspor AS",
  "FC Roche Saint-Genest",
  "SC Preußen 06 Münster",
  "RB Leipzig",
  "UE Santa Coloma",
  "Les Herbiers",
  "Italien",
  "BSC Young Boys",
  "US St Philbert de Grandlieu",
  "Hellas Verona",
  "Racing Santander",
  "FC Geispolsheim 01",
  "West Ham United FC U21",
  "Pd Santa Eulalia",
  "Preston North End",
  "Hereford FC",
  "Terrassa FC",
  "Sestao River Club",
  "FC Torpedo 2008 Kutaisi",
  "FC Fulham",
  "Dinamo Minsk",
  "DC United",
  "Melilla CD",
  "Epinal",
  "FC Südtirol",
  "Calcio Padova",
  "FC Schweighouse Sur Moder",
  "Türkei",
  "Cosenza Calcio",
  "RW Essen",
  "Jura Dolois Fussball",
  "Slowenien",
  "Real Aviles CF",
  "Cheltenham Town",
  "Bodö/Glimt",
  "Al-Shabab FC (SA)",
  "SSV Jahn Regensburg",
  "SSC Neapel",
  "Newport County AFC",
  "FC Teutonia Ottensen 1905",
  "Slowakei",
  "La France D Aizenay",
  "EA Guingamp",
  "Cadiz CF",
  "RC Recreativo de Huelva",
  "Reims Sainte-Anne",
  "SC Bastia",
  "BK Häcken",
  "Club Deportivo Eldense",
  "Stade Brestois 29",
  "Celtic Glasgow",
  "Pd Ergue Gaberic",
  "FC Portsmouth",
  "Cercle Brügge",
  "FC Erzgebirge Aue",
  "NK Olimpija Ljubljana",
  "Schalke 04",
  "Hertha BSC",
  "CP Cacereno SAD",
  "VfL Wolfsburg",
  "FC Ararat Armenia",
  "FK Liepaja",
  "FC Würzburger Kickers",
  "CD Ceuta 6 de Junio",
  "Noisy Le Sec",
  "Colorado Rapids",
  "Pontivy GSI",
  "Forest Green Rovers",
  "England",
  "Atlanta United FC",
  "Sparta Rotterdam",
  "Real Valladolid",
  "FC Cincinnati",
  "Göztepe SK",
  "US Laon",
  "Atletico Lugones",
  "Kayserispor",
  "SD Gernika Club",
  "FC Dinamo Batumi",
  "Gaziantep FK",
  "FC Everton U21",
  "SC Freiburg",
  "CE Manresa",
  "GFK Tikvesh 1930",
  "Virtus Entella",
  "Wrexham AFC",
  "Bergerac Perigord FC",
  "Bristol City",
  "Angouleme Charente FC",
  "Trelissac FC",
  "Real Madrid",
  "Chiclana CF",
  "Croix IC",
  "CD Leganés",
  "AS Domerat",
  "CS Universitatea Craiova 1948",
  "Birmingham City",
  "SO Cholet",
  "VfL Sportfreunde Lotte 1929",
  "Schottland",
  "SK Slavia Prag",
  "Derry City",
  "CD Arenteiro",
  "FK Borac Banja Luka",
  "Bassin D'Arcachon",
  "SC Heerenveen",
  "Sheffield United FC",
  "Riga FC",
  "Football Bourg-En-Bresse Peronnas 01",
  "Paide Linnameeskond",
  "FA Morlaas Est Bearn",
  "Stade Plabennecois",
  "Camon",
  "Hamrun Spartans FC",
  "RSC Anderlecht",
  "FC St. Pauli",
  "US Avellino",
  "BB Bodrumspor",
  "Kilmarnock FC",
  "Ukraine",
  "UD Ibiza",
  "Vierzon FC",
  "Barnet FC",
  "Elche CF",
  "Gil Vicente FC",
  "SS Juve Stabia",
  "FC Differdingen 03",
  "Estrela Amadora",
  "AJ Auxerre",
  "Aston Villa FC U21",
  "FC Dac 1904 Dunajska Streda",
  "Yverdon Sport FC",
  "SK Sturm Graz",
  "FK Shkendija",
  "Coulaines",
  "AS Rosador",
  "Bala Town FC",
  "Asc Le Geldar",
  "FA Siauliai",
  "Squadra Valincu Alta Rocca Rizzanese",
  "UD Las Palmas",
  "FK Transinvest",
  "FC Minnesota United",
  "FK Mornar Bar",
  "Fulham FC U21",
  "Nottingham Forest FC U21",
  "AS Montlouis Football",
  "Frankreich",
  "Al-Qadisiyah",
  "FK Rigas Futbola Skola",
  "Burton Albion",
  "Ramsgate FC",
  "HNK Rijeka",
  "FC Crotone",
  "SC Freiburg II",
  "Brighton & Hove Albion",
  "Larne FC",
  "Chantilly",
  "HB Torshavn",
  "KF Llapi",
  "SD Ponferradina",
  "FC Sarreguemines",
];
export type Team = (typeof teams)[number];

export const tournaments = [
  "UEFA Super Cup 2024",
  "Ligue 1 24/25",
  "EFL Trophy 24/25",
  "3. Liga 24/25",
  "Serie A 24/25",
  "EFL Cup 24/25",
  "DFB Pokal 24/25",
  "3. Liga 23/24",
  "Saudi Prof. League 24/25",
  "Eredivisie 24/25",
  "Supercopa 2025",
  "Trophée des Champions 2024",
  "Super League 24/25",
  "Supercup 2024",
  "Super Cup 23/24",
  "Coppa Italia 23/24",
  "Süper Lig 23/24",
  "UEFA Champions League 24/25",
  "EFL Cup 23/24",
  "FA Cup 23/24",
  "Serie A 23/24",
  "UEFA Europa League 24/25",
  "Coupe de France 23/24",
  "Bundesliga 24/25",
  "Liga Portugal 24/25",
  "Premier League 24/25",
  "Bundesliga AUT 23/24",
  "Europameisterschaft 2024",
  "Copa del Rey 24/25",
  "2. Bundesliga 24/25",
  "UEFA Conference League 24/25",
  "LaLiga 24/25",
  "Major League Soccer 2024",
  "2. Bundesliga 23/24",
  "Bundesliga 23/24",
  "Saudi Prof. League 23/24",
  "Community Shield 2024",
  "Supercup ESP 2024",
  "Coppa Italia 24/25",
  "Copa del Rey 23/24",
  "Süper Lig 24/25",
  "Bundesliga AUT 24/25",
  "Liga Portugal 23/24",
];
export type Tournament = (typeof tournaments)[number];

export type Package = {
  id: number;
  name: string;
  monthly_price_cents: number | null;
  monthly_price_yearly_subscription_in_cents: number;
};

export const packages: Package[] = [
  {
    id: 0,
    name: "MagentaTV - MegaSport",
    monthly_price_cents: null,
    monthly_price_yearly_subscription_in_cents: 6000,
  },
  {
    id: 1,
    name: "ZDF - Free-TV",
    monthly_price_cents: 0,
    monthly_price_yearly_subscription_in_cents: 0,
  },
  {
    id: 2,
    name: "ARD - Free-TV",
    monthly_price_cents: 0,
    monthly_price_yearly_subscription_in_cents: 0,
  },
  {
    id: 3,
    name: "RTL+ - Premium",
    monthly_price_cents: 699,
    monthly_price_yearly_subscription_in_cents: 583,
  },
  {
    id: 4,
    name: "WOW - Live-Sport",
    monthly_price_cents: 3599,
    monthly_price_yearly_subscription_in_cents: 2999,
  },
  {
    id: 5,
    name: "Joyn - Standard",
    monthly_price_cents: 0,
    monthly_price_yearly_subscription_in_cents: 0,
  },
  {
    id: 6,
    name: "waipu.tv - Comfort",
    monthly_price_cents: 749,
    monthly_price_yearly_subscription_in_cents: 749,
  },
  {
    id: 7,
    name: "Vodafone - GigaTV Cable",
    monthly_price_cents: null,
    monthly_price_yearly_subscription_in_cents: 1249,
  },
  {
    id: 8,
    name: "Zattoo - FREE",
    monthly_price_cents: 0,
    monthly_price_yearly_subscription_in_cents: 0,
  },
  {
    id: 9,
    name: "Amazon - Prime Video",
    monthly_price_cents: 899,
    monthly_price_yearly_subscription_in_cents: 749,
  },
  {
    id: 10,
    name: "DAZN - Unlimited",
    monthly_price_cents: 4499,
    monthly_price_yearly_subscription_in_cents: 3499,
  },
  {
    id: 11,
    name: "Sky - Bundesliga",
    monthly_price_cents: null,
    monthly_price_yearly_subscription_in_cents: 3000,
  },
  {
    id: 12,
    name: "Zattoo - SMART HD",
    monthly_price_cents: 649,
    monthly_price_yearly_subscription_in_cents: 649,
  },
  {
    id: 13,
    name: "Sky - Sport",
    monthly_price_cents: null,
    monthly_price_yearly_subscription_in_cents: 2500,
  },
  {
    id: 14,
    name: "Sky - Sport und Bundesliga",
    monthly_price_cents: null,
    monthly_price_yearly_subscription_in_cents: 3500,
  },
  {
    id: 15,
    name: "DAZN - World",
    monthly_price_cents: 999,
    monthly_price_yearly_subscription_in_cents: 699,
  },
  {
    id: 16,
    name: "DAZN - Super Sports",
    monthly_price_cents: 2499,
    monthly_price_yearly_subscription_in_cents: 1999,
  },
  {
    id: 17,
    name: "DAZN - Free",
    monthly_price_cents: 0,
    monthly_price_yearly_subscription_in_cents: 0,
  },
  {
    id: 18,
    name: "MagentaTV - Smart",
    monthly_price_cents: 1500,
    monthly_price_yearly_subscription_in_cents: 1500,
  },
  {
    id: 19,
    name: "MagentaTV - Flex",
    monthly_price_cents: 1000,
    monthly_price_yearly_subscription_in_cents: 1000,
  },
  {
    id: 20,
    name: "MagentaTV - Sport",
    monthly_price_cents: 1995,
    monthly_price_yearly_subscription_in_cents: 1295,
  },
  {
    id: 21,
    name: "Sport1 - Free-TV",
    monthly_price_cents: 0,
    monthly_price_yearly_subscription_in_cents: 0,
  },
  {
    id: 22,
    name: "Sat1 - Free-TV",
    monthly_price_cents: 0,
    monthly_price_yearly_subscription_in_cents: 0,
  },
  {
    id: 23,
    name: "Sportdigital - Free",
    monthly_price_cents: 0,
    monthly_price_yearly_subscription_in_cents: 0,
  },
  {
    id: 24,
    name: "Sportdigital - Premium",
    monthly_price_cents: 499,
    monthly_price_yearly_subscription_in_cents: 375,
  },
  {
    id: 25,
    name: "Zattoo - SMART HD mit Plus Sport",
    monthly_price_cents: 1239,
    monthly_price_yearly_subscription_in_cents: 1239,
  },
  {
    id: 26,
    name: "RTL - Free-TV",
    monthly_price_cents: 0,
    monthly_price_yearly_subscription_in_cents: 0,
  },
  {
    id: 27,
    name: "Bild - Bildplus",
    monthly_price_cents: 199,
    monthly_price_yearly_subscription_in_cents: 199,
  },
  {
    id: 28,
    name: "Bildplus/Amazon - Bildplus/Amazon Prime Video",
    monthly_price_cents: 899,
    monthly_price_yearly_subscription_in_cents: 899,
  },
  {
    id: 29,
    name: "Digiturk - Fußball + Family",
    monthly_price_cents: null,
    monthly_price_yearly_subscription_in_cents: 992,
  },
  {
    id: 30,
    name: "waipu.tv - Perfect Plus",
    monthly_price_cents: 1299,
    monthly_price_yearly_subscription_in_cents: 1299,
  },
  {
    id: 31,
    name: "waipu.tv - Perfect Plus DAZN",
    monthly_price_cents: 5499,
    monthly_price_yearly_subscription_in_cents: 4499,
  },
  {
    id: 32,
    name: "O2 - TV M",
    monthly_price_cents: 699,
    monthly_price_yearly_subscription_in_cents: 699,
  },
  {
    id: 33,
    name: "O2 - TV M mit Pay-TV",
    monthly_price_cents: 1398,
    monthly_price_yearly_subscription_in_cents: 1398,
  },
  {
    id: 34,
    name: "Vodafone - GigaTV Cable Premium Plus",
    monthly_price_cents: null,
    monthly_price_yearly_subscription_in_cents: 2332,
  },
  {
    id: 35,
    name: "Apple - MLS Season Pass",
    monthly_price_cents: 1499,
    monthly_price_yearly_subscription_in_cents: 825,
  },
  {
    id: 36,
    name: "SportWorld - Samsung Sport Paket",
    monthly_price_cents: 1499,
    monthly_price_yearly_subscription_in_cents: 1499,
  },
];
